name: Tests

on: 
 - push

jobs:
  run-puppeteer:
    name: Run puppeteer tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v2
      env:
        PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'

    - name: Prepare modules
      run: npm install

    - name: Test Code
      uses: mujo-code/puppeteer-headful@master
      with:
        args: npm test
    
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: my-artifact
        path: failedTests
