name: Tests

on: 
 - push

jobs:
  run-puppeteer:
    name: Run puppeteer tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v2

    - name: Prepare dependencies
      run: sudo apt-get install xvfb && npm install
    
    - name: Test Code
      run: xvfb-run npm test
