name: CI
on: push
jobs:
  installDependencies:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js
      uses: actions/setup-node@v1
      env:
        PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'
    - run: npm install
    - name: Test Code
      uses: mujo-code/puppeteer-headful@master
      with:
        args: npm test